# testing file for Travis
# https://github.com/neuropoly/ivado-medical-imaging
language: python
python:
  - "3.6"
  - "3.7"


matrix:
  include:
    - os: linux  # list of Linux env: https://docs.travis-ci.com/user/reference/overview/
      name: "Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
    - os: linux
      name: "Ubuntu 16.04 (Xenial)"
      dist: xenial
    - os: linux
      name: "Ubuntu 14.04 (Trusty)"
      dist: trusty
    - os: osx  # list of OSX env: https://docs.travis-ci.com/user/reference/osx/
      name: "OSX 10.14 (Mojave)"
      osx_image: xcode11.2
    - os: osx
      name: "OSX 10.13 (High Sierra)"
      osx_image: xcode9.4
    - os: osx
      name: "OSX 10.12 (Sierra)"
      osx_image: xcode9.2

install:
  - python -m pip install --upgrade pip
  - pip install -e .

script:
  - |
    echo *** UNIT TESTS ***
    pytest
