# testing file for Travis
# https://github.com/neuropoly/ivado-medical-imaging
language: python
# ===== Linux ======
dist:
  - xenial
  - bionic
  - trusty

python:
  - 3.5
  - 3.6
  - 3.7
matrix:
  include:
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      install: pip3 install -e .
      script:
        -
          echo *** UNIT TESTS ***
          travis_wait 30 pytest
      after_success: python 3 -m codecov

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install: pip install -e .

script:
  -
    echo *** UNIT TESTS ***
    pytest
